[package]
authors = ["Aleksandr Susha <isushik94@gmail.com>"]
edition = "2018"
name    = "exec"
publish = false
version = "0.1.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dummy-dylib = { path = "../dummy-dylib" }
